dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "https://jcenter.bintray.com"
        }

        mavenCentral()

    }
}
rootProject.name = "Meal Management"
include ':app'
include ':monthPicker'
